<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	$title = $this->translate("monthlytimesheetreport_pagetitle"); 
	$this->headTitle($title);
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setFilterColumns(array("td.employeeid"));

	$paginate->processPost($request->getParams());
	
	$month_filter = date("n"); 
	if (!isEmptyString($request->month)) {
		$month_filter = $request->month; 
	}
	
	$year_filter = date("Y"); 
	if (!isEmptyString($request->year)) {
		$year_filter = $request->year; 
	}
	
	$billable_results_query = "SELECT MONTH(td.hours) as `month`, DATE_FORMAT(t.weekendingdate, '%e-%b') AS 'Week Ending', p.jobnumber AS 'JOB NUMBER', SUM(IF(WEEKDAY(td.workday) = 5, td.`hours`, 0)) AS SAT,SUM(IF(WEEKDAY(td.workday) = 6, td.`hours`, 0)) AS SUN,SUM(IF(WEEKDAY(td.workday) = 0, td.`hours`, 0)) AS MON,SUM(IF(WEEKDAY(td.workday) = 1, td.`hours`, 0)) AS TUE,SUM(IF(WEEKDAY(td.workday) = 2, td.`hours`, 0)) AS WED,SUM(IF(WEEKDAY(td.workday) = 3, td.`hours`, 0)) AS THUR,SUM(IF(WEEKDAY(td.workday) = 4, td.`hours`, 0)) AS FRI,SUM(td.`hours`) AS 'TOTAL HOURS'
FROM timesheetdetail td INNER JOIN timesheet t ON td.`timesheetid` = t.`id` INNER JOIN project p ON td.`projectid` = p.id WHERE p.type = 1 AND YEAR(td.workday) = '".$year_filter."' AND MONTH(td.workday) = '".$month_filter."' ".$paginate->getSearchAndFilterSQL()."
GROUP BY td.employeeid, td.`projectid`, t.weekendingdate HAVING SUM(td.`hours`) > 0 ORDER BY t.weekendingdate, p.jobnumber DESC"; // billable hours
	//debugMessage($billable_results_query);
	$non_billable_results_query = "SELECT MONTH(td.hours) as `month`, DATE_FORMAT(t.weekendingdate, '%e-%b') AS 'Week Ending', p.jobnumber AS 'JOB NUMBER', SUM(IF(WEEKDAY(td.workday) = 5, td.`hours`, 0)) AS SAT,SUM(IF(WEEKDAY(td.workday) = 6, td.`hours`, 0)) AS SUN,SUM(IF(WEEKDAY(td.workday) = 0, td.`hours`, 0)) AS MON,SUM(IF(WEEKDAY(td.workday) = 1, td.`hours`, 0)) AS TUE,SUM(IF(WEEKDAY(td.workday) = 2, td.`hours`, 0)) AS WED,SUM(IF(WEEKDAY(td.workday) = 3, td.`hours`, 0)) AS THUR,SUM(IF(WEEKDAY(td.workday) = 4, td.`hours`, 0)) AS FRI,SUM(td.`hours`) AS 'TOTAL HOURS' 
FROM timesheetdetail td INNER JOIN timesheet t ON td.`timesheetid` = t.`id` INNER JOIN project p ON td.`projectid` = p.id WHERE p.type = 0 AND YEAR(td.workday) = '".$year_filter."' AND MONTH(td.workday) = '".$month_filter."' ".$paginate->getSearchAndFilterSQL()."
GROUP BY td.employeeid, td.`projectid`, t.weekendingdate HAVING SUM(td.`hours`) > 0  ORDER BY t.weekendingdate, p.jobnumber DESC"; // non billable hours

	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $billable_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $billable_results_query);
	# the query string to be appended to the return to list URL
	$session->setVar('list_query_string'.$request->getControllerName(), $request->getParams());
	
	# This variable stores the number of redundant columns returned in the query so that when we are printing
	# we are able to know how many columns to ignore. This variable is sent in the print URL
	$number_of_redundant_columns = "1";
	
	# the columns which contain numbers in the invoice query
	# Please note that the column count begins at 0
	$export_number_column_list = "0";
	
	$url_to_generate_excel = $this->baseUrl('report/monthlytimesheetreport?month='.$month_filter.'&year='.$year_filter.'&td__employeeid='.$request->td__employeeid.'&submit=submit&'.PAGE_CONTENTS_ONLY.'=true');
	//debugMessage("URL: ".$url_to_generate_excel);
	
?>
<style>
table.formtable td {
/*padding-right: 30px;*/
}
table.formtable {
	border-left:solid 1px #000000;
	border-bottom:solid 1px #000000;
}
table.formtable td {
	border-right:solid 1px #000000;
	border-top:solid 1px #000000;
	height:20px;
	padding-left: 10px;/**padding-left: 14px;*//*padding-right: 30px;*/
}
</style>
<?php if($request->pgc != "true"){ ?>
<script>
	$(document).ready(function(){
		$("#monthlytimesheetreportsearchform").validate({		
			// define the validation rules one field at a time
			rules: {
				<?php echo 'td'.HTML_TABLE_COLUMN_SEPARATOR.'employeeid'; ?>: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {				
				<?php echo 'td'.HTML_TABLE_COLUMN_SEPARATOR.'employeeid'; ?>: "<?php echo $this->translate("monthlytimesheetreport_employee_error"); ?>"
			},
			// update error location for content type
			errorPlacement: function(error, element) {
				error.appendTo("#reportparametererror");
			}
		});
	});
</script>
<form action="<?php echo $this->baseUrl("report/monthlytimesheetreport"); ?>" method="get" id="monthlytimesheetreportsearchform">
  <b>Report Options:</b> <br />
  <?php		
	 $monthdropdown = new Zend_Form_Element_Select('month',
								array(
						'multiOptions' => getAllMonthsAsNumbers(),						
						'view' => new Zend_View(),
									 'decorators' => array('ViewHelper'),
									  'class' => array('chzn-select', 'month')		
								)
						  );
						  
	 $monthdropdown->setValue($month_filter);
	 echo $monthdropdown->render(); 
?>
  &nbsp; &nbsp;
  <?php		
									 $yeardropdown = new Zend_Form_Element_Select('year',
																array(
														'multiOptions' => getAllYearsForMonthlyTimeReport(),						
														'view' => new Zend_View(),
																	 'decorators' => array('ViewHelper'),
																	 'class' => array('chzn-select', 'year')							
																)
														  );
														  
									 $yeardropdown->setValue($year_filter);
									 echo $yeardropdown->render(); 
						  ?>
  &nbsp; &nbsp;
  <?php 	
									$employeelookup = new LookupType();
									$employeelookup->setName("ALL_USERS"); 
									$employeedropdown = new Zend_Form_Element_Select('td'.HTML_TABLE_COLUMN_SEPARATOR.'employeeid',
												array(
													'multiOptions' => array_merge_maintain_keys(array("" => $this->translate('monthlytimesheetreport_list_filter_employee')), $employeelookup->getOptionValuesFromQuery()), 
													'view' => new Zend_View(),
													'decorators' => array('ViewHelper'),
													'class' => array('chzn-select')			
												)
											);
									$employeedropdown->setValue($request->getParam('td'.HTML_TABLE_COLUMN_SEPARATOR.'employeeid')); 
									echo $employeedropdown->render();	
    	?>
  &nbsp; &nbsp;
  <button value="submit" name="submit" type="submit" class="positiveaction" title="<?php echo $this->translate('report_button_generate'); ?>"><img src="<?php echo $this->baseUrl("images/zoom_in.png"); ?>" alt="<?php echo $this->translate('report_generate'); ?>"/><?php echo $this->translate('report_button_generate'); ?></button>
  <br />
  <div id="reportparametererror"></div>
</form>
<h1><?php echo $title; ?></h1>
<?php } ?>
<?php
if (isEmptyString($request->submit)) {
	?>
<label class="informationmessage"><?php echo $this->translate("monthlytimesheetreport_select_employee"); ?></label>
<?php 
	require_once APPLICATION_PATH.'/includes/footer.php';
}  else {
	$conn = Doctrine_Manager::connection(); 
	
	$useraccount = new UserAccount();
	$useraccount->populate($request->getParam('td__employeeid'));
	
	$unapproved_check = "SELECT t.id, DATE_FORMAT(t.weekendingdate, '".$config->dateandtime->mysqlmediumformat."') AS 'Week Ending', lv.lookupvaluedescription AS `Status` FROM timesheet t INNER JOIN lookuptypevalue AS lv ON (t.`status` = lv.lookuptypevalue AND lv.lookuptypeid = 6) WHERE status IN (0, 1, 3) AND YEAR(t.weekendingdate) = '".$year_filter."' AND MONTH(t.weekendingdate) = '".$month_filter."' AND t.employeeid = '".$request->getParam('td__employeeid')."' ORDER BY t.weekendingdate ";
	$unapproved_checkresult = $conn->fetchAll($unapproved_check); 
	
	if (count($unapproved_checkresult) != 0) {
		// there are unapproved timesheets so show them 
	?>
<label class="informationmessage"><?php echo sprintf($this->translate('monthlytimesheetreport_unapproved_error'), $useraccount->getName(), date("M t, Y", strtotime($year_filter."-".$month_filter."-01"))); ?></label>
<table class="list">
  <thead>
    <tr>
      <td><?php echo $this->translate('timesheet_weekendingdate_label'); ?></td>
      <td><?php echo $this->translate('timesheet_status_label'); ?></td>
    </tr>
  </thead>
  <tbody>
    <?php 
		foreach ($unapproved_checkresult as $line) {
	?>
    <tr>
      <td><a href="<?php echo $this->baseUrl('timesheet/view/id/'.encode($line['id'])); ?>" title="<?php echo $this->translate(''); ?>"><?php echo $line['Week Ending']; ?></a></td>
      <td><?php echo $line['Status']; ?></td>
    </tr>
    <?php 
		}
	?>
  </tbody>
</table>
<?php 
	} else {
		// all the timesheets for the employee in the month have been approved so show the report
		$billable_result = $conn->fetchAll($billable_results_query);
		$non_billable_result = $conn->fetchAll($non_billable_results_query);
		
		// check billable hours first
		$has_no_data = (count($billable_result) == 0) ? true : false;
		
		// now check non billable hours if there are no billable hours 
		if ($has_no_data) {
			$has_no_data = (count($non_billable_result) == 0) ? true : false;
		}
	
		if ($has_no_data) {
			?>
<label class="informationmessage"><?php echo $this->translate("monthlytimesheetreport_no_records"); ?></label>
<?php 
		} else { ?>
<?php if($request->pgc != "true"){ ?>
<a class="positiveaction" href="javascript:openPopUpWindow('<?php echo $url_to_generate_excel; ?>');"><img src="<?php echo $this->baseUrl('images/excel.png'); ?>" /><?php echo $this->translate("weeklystatusreport_button_download_timesheetreport"); ?></a>
<?php } ?>
<table class="formtable" border="0">
  <tr style="background-color:#C0C0C0;">
    <td style="border-right:none; border-bottom:none;"><b>Company:</b></td>
    <td style="border-right:none; border-bottom:none;"><?php echo $useraccount->getCompanyName(); ?></td>
    <td style="border-left:none; border-right:none; border-bottom:none;">&nbsp;</td>
    <td style="border-left:none; border-right:none; border-bottom:none;">&nbsp;</td>
    <td style="border-left:none; border-right:none; border-bottom:none;">&nbsp;</td>
    
    <td style="border-left:none; border-bottom:none; border-right:none;">&nbsp;</td>
    <td style="border-left:none; border-right:none; border-bottom:none;">&nbsp;</td>
    <td style="border-left:none; border-bottom:none; border-right:none;">&nbsp;</td>
    <td style="border-right:none; border-left:none; border-bottom:none;"><b>Employee:</b></td>
    <td style="border-right:none; border-left:none; border-right:none; border-bottom:none;"><?php echo $useraccount->getName(); ?></td>
  </tr>
  <tr style="background-color:#C0C0C0;">
    <td style="border-right:none; border-top:none;"><b>Address:</b></td>
    <td style="border-right:none; border-top:none;"><?php echo nl2br($useraccount->getCompanyAddress()); ?></td>
    <td style="border-left:none; border-right:none; border-top:none;">&nbsp;</td>
    <td style="border-left:none; border-right:none; border-top:none;">&nbsp;</td>
    <td style="border-left:none; border-right:none; border-top:none;">&nbsp;</td>
    
    <td style="border-left:none; border-right:none; border-top:none;">&nbsp;</td>
    <td style="border-left:none; border-top:none; border-right:none;">&nbsp;</td>
    <td style="border-left:none; border-top:none; border-right:none;">&nbsp;</td><td style="border-left:none; border-right:none; border-top:none;"><b>Title:</b></td>
    <td style="border-left:none; border-right:none; border-top:none;"><?php echo $useraccount->getJobTitle(); ?></td>
  </tr>
</table>
<table class="formtable">
  <tr style="background-color:#CCFFFF;">
    <td colspan="10">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="5">&nbsp;</td>
    <td colspan="5" class="label"><b>MONTH ENDING: <?php echo  date("M t Y", strtotime($year_filter."-".$month_filter."-01")); ?></b></td>
  </tr>
  <tr>
    <td style="background-color:#CCFFFF;" colspan="5">&nbsp;</td>
    <td style="background-color:#CCFFFF;" colspan="5" class="label">&nbsp;</td>
  </tr>
  <tr style="font-weight:bold;">
    <td align="center">Week Ending:</td>
    <td align="center">JOB NUMBER</td>
    <td align="center">SAT</td>
    <td align="center">SUN</td>
    <td align="center">MON</td>
    <td align="center">TUE</td>
    <td align="center">WED</td>
    <td align="center">THUR</td>
    <td align="center">FRI</td>
    <td align="center">TOTAL HOURS</td>
  </tr>
  <?php 
					$hours_by_day = array(); 
					foreach ($billable_result as $line) {
						$hours_by_day['MON'][] = $line['MON']; 
						$hours_by_day['TUE'][] = $line['TUE']; 
						$hours_by_day['WED'][] = $line['WED']; 
						$hours_by_day['THUR'][] = $line['THUR']; 
						$hours_by_day['FRI'][] = $line['FRI']; 
						$hours_by_day['SAT'][] = $line['SAT']; 
						$hours_by_day['SUN'][] = $line['SUN']; 
						$hours_by_day['TOTAL HOURS'][] = $line['TOTAL HOURS']; 
					?>
  <tr>
    <td align="right"><?php echo $line['Week Ending']; ?></td>
    <td style="background-color:#CCFFFF;" align="center"><?php echo $line['JOB NUMBER']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['SAT']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['SUN']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['MON']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['TUE']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['WED']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['THUR']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['FRI']; ?></td>
    <td align="right" style="vnd.ms-excel.numberformat:0.00;"><?php echo $line['TOTAL HOURS']; ?></td>
  </tr>
  <?php }?>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <?php 
		foreach ($non_billable_result as $line) {
			$hours_by_day['MON'][] = $line['MON']; 
			$hours_by_day['TUE'][] = $line['TUE']; 
			$hours_by_day['WED'][] = $line['WED']; 
			$hours_by_day['THUR'][] = $line['THUR']; 
			$hours_by_day['FRI'][] = $line['FRI']; 
			$hours_by_day['SAT'][] = $line['SAT']; 
			$hours_by_day['SUN'][] = $line['MON']; 
			$hours_by_day['TOTAL HOURS'][] = $line['TOTAL HOURS']; 
		?>
  <tr>
    <td align="right"><?php echo $line['Week Ending']; ?></td>
    <td style="background-color:#CCFFFF;" align="center"><?php echo $line['JOB NUMBER']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['SAT']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['SUN']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['MON']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['TUE']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['WED']; ?></td>
    <td style="background-color:#CCFFFF vnd.ms-excel.numberformat:0.00;;" align="right"><?php echo $line['THUR']; ?></td>
    <td style="background-color:#CCFFFF; vnd.ms-excel.numberformat:0.00;" align="right"><?php echo $line['FRI']; ?></td>
    <td align="right" style="vnd.ms-excel.numberformat:0.00;"><?php echo $line['TOTAL HOURS']; ?></td>
  </tr>
  <?php }?>
  <tr>
    <td style="border-left:none; border-bottom:none;">&nbsp;</td>
    <td style="font-weight:bold;">TOTAL</td>
    <td align="right" style="vnd.ms-excel.numberformat:0.00;"><?php echo formatNumber(array_sum($hours_by_day['SAT'])); ?></td>
    <td align="right" style="vnd.ms-excel.numberformat:0.00;"><?php echo formatNumber(array_sum($hours_by_day['SUN'])); ?></td>
    <td align="right" style="vnd.ms-excel.numberformat:0.00;"><?php echo formatNumber(array_sum($hours_by_day['MON'])); ?></td>
    <td align="right" style="vnd.ms-excel.numberformat:0.00;"><?php echo formatNumber(array_sum($hours_by_day['TUE'])); ?></td>
    <td align="right" style="vnd.ms-excel.numberformat:0.00;"><?php echo formatNumber(array_sum($hours_by_day['WED'])); ?></td>
    <td align="right" style="vnd.ms-excel.numberformat:0.00;"><?php echo formatNumber(array_sum($hours_by_day['THUR'])); ?></td>
    <td align="right" style="vnd.ms-excel.numberformat:0.00;"><?php echo formatNumber(array_sum($hours_by_day['FRI'])); ?></td>
    <td align="right" style="font-weight:bold; background-color:#00FF00;vnd.ms-excel.numberformat:0.00;"><?php echo formatNumber(array_sum($hours_by_day['TOTAL HOURS'])); ?></td>
  </tr>
</table>
<?php 
		} // end else 
	} // end check for unapproved timesheets
	require_once APPLICATION_PATH.'/includes/footer.php';
} // end check for whether the form has been submitted 
?>
