<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	$title = $this->translate("monthlytimesheetreport_pagetitle"); 
	$this->headTitle($title);
	
	// the config object instance
	$config = Zend_Registry::get('config'); 
		
	$session = SessionWrapper::getInstance();
	
	$month_filter = date("n"); 
	if (!isEmptyString($this->month)) {
		$month_filter = $this->month; 
	}
	
	$year_filter = date("Y"); 
	if (!isEmptyString($this->year)) {
		$year_filter = $this->year; 
	}
	
	$billable_results_query = "SELECT MONTH(td.hours) as `month`, DATE_FORMAT(t.weekendingdate, '%e-%b') AS 'Week Ending', p.jobnumber AS 'JOB NUMBER', SUM(IF(WEEKDAY(td.workday) = 5, td.`hours`, 0)) AS SAT,SUM(IF(WEEKDAY(td.workday) = 6, td.`hours`, 0)) AS SUN,SUM(IF(WEEKDAY(td.workday) = 0, td.`hours`, 0)) AS MON,SUM(IF(WEEKDAY(td.workday) = 1, td.`hours`, 0)) AS TUE,SUM(IF(WEEKDAY(td.workday) = 2, td.`hours`, 0)) AS WED,SUM(IF(WEEKDAY(td.workday) = 3, td.`hours`, 0)) AS THUR,SUM(IF(WEEKDAY(td.workday) = 4, td.`hours`, 0)) AS FRI,SUM(td.`hours`) AS 'TOTAL HOURS'
FROM timesheetdetail td INNER JOIN timesheet t ON td.`timesheetid` = t.`id` INNER JOIN project p ON td.`projectid` = p.id WHERE p.type = 1 AND YEAR(td.workday) = '".$year_filter."' AND MONTH(td.workday) = '".$month_filter."' AND td.employeeid = '".$this->td__employeeid."' 
GROUP BY td.employeeid, td.`projectid`, t.weekendingdate HAVING SUM(td.`hours`) > 0 ORDER BY t.weekendingdate, p.jobnumber DESC"; // billable hours
	//debugMessage($billable_results_query);
	
	$non_billable_results_query = "SELECT MONTH(td.hours) as `month`, DATE_FORMAT(t.weekendingdate, '%e-%b') AS 'Week Ending', p.jobnumber AS 'JOB NUMBER', SUM(IF(WEEKDAY(td.workday) = 5, td.`hours`, 0)) AS SAT,SUM(IF(WEEKDAY(td.workday) = 6, td.`hours`, 0)) AS SUN,SUM(IF(WEEKDAY(td.workday) = 0, td.`hours`, 0)) AS MON,SUM(IF(WEEKDAY(td.workday) = 1, td.`hours`, 0)) AS TUE,SUM(IF(WEEKDAY(td.workday) = 2, td.`hours`, 0)) AS WED,SUM(IF(WEEKDAY(td.workday) = 3, td.`hours`, 0)) AS THUR,SUM(IF(WEEKDAY(td.workday) = 4, td.`hours`, 0)) AS FRI,SUM(td.`hours`) AS 'TOTAL HOURS' 
FROM timesheetdetail td INNER JOIN timesheet t ON td.`timesheetid` = t.`id` INNER JOIN project p ON td.`projectid` = p.id WHERE p.type = 0 AND YEAR(td.workday) = '".$year_filter."' AND MONTH(td.workday) = '".$month_filter."'  AND td.employeeid = '".$this->td__employeeid."'
GROUP BY td.employeeid, td.`projectid`, t.weekendingdate HAVING SUM(td.`hours`) > 0  ORDER BY t.weekendingdate, p.jobnumber DESC"; // non billable hours
	//debugMessage($non_billable_results_query);
	
	// generate the temp file name to store the HTML contents
	$timestamp = time().rand(100, 5000);
	$temp_file_name = md5($timestamp).".html";
	//debugMessage($temp_file_name);
  
	$url_to_generate_excel = $this->baseUrl('report/monthlytimesheetreport?month='.$month_filter.'&year='.$year_filter.'&td__employeeid='.$this->td__employeeid.'&submit=submit&'.PAGE_CONTENTS_ONLY.'=true');
	//debugMessage("URL: ".$url_to_generate_excel);
  
	$weeklystatusreport_html = "";
?>
<style>
table.formtable td {
	padding-right: 30px;
}
</style>
<?php
if (isEmptyString($this->submit)) {
	?>
<label class="informationmessage"><?php echo $this->translate("monthlytimesheetreport_select_employee"); ?></label>
<?php 
	require_once APPLICATION_PATH.'/includes/footer.php';
}  else {
	$conn = Doctrine_Manager::connection(); 
	
	$useraccount = new UserAccount();
	$useraccount->populate($this->td__employeeid);
	
	$unapproved_check = "SELECT t.id, DATE_FORMAT(t.weekendingdate, '".$config->dateandtime->mysqlmediumformat."') AS 'Week Ending', lv.lookupvaluedescription AS `Status` FROM timesheet t INNER JOIN lookuptypevalue AS lv ON (t.`status` = lv.lookuptypevalue AND lv.lookuptypeid = 6) WHERE status IN (0, 1, 3) AND YEAR(t.weekendingdate) = '".$year_filter."' AND MONTH(t.weekendingdate) = '".$month_filter."' AND t.employeeid = '".$this->td__employeeid."' ORDER BY t.weekendingdate ";
	$unapproved_checkresult = $conn->fetchAll($unapproved_check); 
	
	if (count($unapproved_checkresult) != 0) {
		// there are unapproved timesheets so show them 
	?>
<label class="informationmessage"><?php echo sprintf($this->translate('monthlytimesheetreport_unapproved_error'), $useraccount->getName(), date("M t, Y", strtotime($year_filter."-".$month_filter."-01"))); ?></label>
<table class="list">
  <thead>
    <tr>
      <td><?php echo $this->translate('timesheet_weekendingdate_label'); ?></td>
      <td><?php echo $this->translate('timesheet_status_label'); ?></td>
    </tr>
  </thead>
  <tbody>
    <?php 
					foreach ($unapproved_checkresult as $line) {
				?>
    <tr>
      <td><a href="<?php echo $this->baseUrl('timesheet/view/id/'.encode($line['id'])); ?>" title="<?php echo $this->translate(''); ?>"><?php echo $line['Week Ending']; ?></a></td>
      <td><?php echo $line['Status']; ?></td>
    </tr>
    <?php 
					}
				?>
  </tbody>
</table>
<?php 
		
	} else {
		// all the timesheets for the employee in the month have been approved so show the report
		$billable_result = $conn->fetchAll($billable_results_query);
		$non_billable_result = $conn->fetchAll($non_billable_results_query);
		
		// check billable hours first
		$has_no_data = (count($billable_result) == 0) ? true : false;
		
		// now check non billable hours if there are no billable hours 
		if ($has_no_data) {
			$has_no_data = (count($non_billable_result) == 0) ? true : false;
		}
	
		if ($has_no_data) {
			?>
<label class="informationmessage"><?php echo $this->translate("monthlytimesheetreport_no_records"); ?></label>
<?php 
		} else { ?>
<a class="positiveaction" href="javascript:openPopUpWindow('<?php echo $url_to_generate_excel; ?>');"><img src="<?php echo $this->baseUrl('images/printer.png'); ?>" /><?php echo $this->translate("weeklystatusreport_button_print_weeklystatusreport"); ?></a>
<table class="formtable" border="0" style="background-color:#C0C0C0;">
  <tr>
    <td class="label">Company: </td>
    <td><?php echo $useraccount->getCompanyName(); ?></td>
    <td class="label">Employee:</td>
    <td><?php echo $useraccount->getName(); ?></td>
  </tr>
  <tr>
    <td class="label">Address:</td>
    <td><?php echo nl2br($useraccount->getCompanyAddress()); ?></td>
    <td class="label">Title:</td>
    <td><?php echo $useraccount->getJobTitle(); ?></td>
  </tr>
</table>
<table class="formtable">
  <tr style="background-color:#CCFFFF;">
    <td colspan="10">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="5">&nbsp;</td>
    <td colspan="5" class="label">MONTH ENDING: <?php echo  date("M t Y", strtotime($year_filter."-".$month_filter."-01")); ?></td>
  </tr>
  <tr style="background-color:#CCFFFF;">
    <td colspan="5">&nbsp;</td>
    <td colspan="5" class="label">&nbsp;</td>
  </tr>
  <tr style="font-weight:bold;">
    <td align="right">Week Ending:</td>
    <td align="right">JOB NUMBER</td>
    <td align="right">SAT</td>
    <td align="right">SUN</td>
    <td align="right">MON</td>
    <td align="right">TUE</td>
    <td align="right">WED</td>
    <td align="right">THUR</td>
    <td align="right">FRI</td>
    <td align="right">TOTAL HOURS</td>
  </tr>
  <?php 
					$hours_by_day = array(); 
					foreach ($billable_result as $line) {
						$hours_by_day['MON'][] = $line['MON']; 
						$hours_by_day['TUE'][] = $line['TUE']; 
						$hours_by_day['WED'][] = $line['WED']; 
						$hours_by_day['THUR'][] = $line['THUR']; 
						$hours_by_day['FRI'][] = $line['FRI']; 
						$hours_by_day['SAT'][] = $line['SAT']; 
						$hours_by_day['SUN'][] = $line['MON']; 
						$hours_by_day['TOTAL HOURS'][] = $line['TOTAL HOURS']; 
					?>
  <tr>
    <td align="right"><?php echo $line['Week Ending']; ?></td>
    <td style="background-color:#CCFFFF;" align="center"><?php echo $line['JOB NUMBER']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['SAT']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['SUN']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['MON']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['TUE']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['WED']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['THUR']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['FRI']; ?></td>
    <td align="right"><?php echo $line['TOTAL HOURS']; ?></td>
  </tr>
  <?php }?>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <?php 
					foreach ($non_billable_result as $line) {
						$hours_by_day['MON'][] = $line['MON']; 
						$hours_by_day['TUE'][] = $line['TUE']; 
						$hours_by_day['WED'][] = $line['WED']; 
						$hours_by_day['THUR'][] = $line['THUR']; 
						$hours_by_day['FRI'][] = $line['FRI']; 
						$hours_by_day['SAT'][] = $line['SAT']; 
						$hours_by_day['SUN'][] = $line['MON']; 
						$hours_by_day['TOTAL HOURS'][] = $line['TOTAL HOURS']; 
					?>
  <tr>
    <td align="right"><?php echo $line['Week Ending']; ?></td>
    <td style="background-color:#CCFFFF;" align="center"><?php echo $line['JOB NUMBER']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['SAT']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['SUN']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['MON']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['TUE']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['WED']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['THUR']; ?></td>
    <td style="background-color:#CCFFFF;" align="right"><?php echo $line['FRI']; ?></td>
    <td align="right"><?php echo $line['TOTAL HOURS']; ?></td>
  </tr>
  <?php }?>
  <tr>
    <td>&nbsp;</td>
    <td style="font-weight:bold;">TOTAL</td>
    <td align="right"><?php echo formatNumber(array_sum($hours_by_day['SAT'])); ?></td>
    <td align="right"><?php echo formatNumber(array_sum($hours_by_day['SUN'])); ?></td>
    <td align="right"><?php echo formatNumber(array_sum($hours_by_day['MON'])); ?></td>
    <td align="right"><?php echo formatNumber(array_sum($hours_by_day['TUE'])); ?></td>
    <td align="right"><?php echo formatNumber(array_sum($hours_by_day['WED'])); ?></td>
    <td align="right"><?php echo formatNumber(array_sum($hours_by_day['THUR'])); ?></td>
    <td align="right"><?php echo formatNumber(array_sum($hours_by_day['FRI'])); ?></td>
    <td align="right" style="font-weight:bold; background-color:#00FF00;"><?php echo formatNumber(array_sum($hours_by_day['TOTAL HOURS'])); ?></td>
  </tr>
</table>
<?php 
			// for PROD, there we use public_html
			$publicfolder = "/public/";
			if (APPLICATION_ENV == "production") {
				$publicfolder = "/public_html/";
			}
		
			$monthlytimesheetdetailreport_html = ob_get_contents();
			//debugMessage($weeklystatusreport_html);
			$monthlytimesheetdetailreport_html .= "<br /><br /><br /><span style=\"font-size:8px;\">Report generated from www.staff-atechra.com.com on ".date($config->dateandtime->reportgenerationtimestamp).". For more information contact support@staff-atechra.com</span>";
			$printbutton_html = '<a class="positiveaction" href="javascript:openPopUpWindow(\''.$url_to_generate_excel.'\');"><img src="'.$this->baseUrl("images/printer.png").'" />'.$this->translate("weeklystatusreport_button_print_weeklystatusreport").'</a>';
			// remove the print button from the final HTML used to generate the PDF document
			$weeklystatusreport_html = str_replace($printbutton_html, "", $monthlytimesheetdetailreport_html);
			
			// Add the CSS to style the report for PDF generation 
			$style_sheet = '<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-15"><style type="text/css">'.file_get_contents(str_replace("application", "", APPLICATION_PATH).$publicfolder.'/stylesheets/9.atechra.css').'</style></head>'; 
	
			$session->setVar('weeklystatusreport', $style_sheet."<body>".$weeklystatusreport_html."</body></html>"); 
			
			// write the HTML file to the file system 
			file_put_contents(str_replace("application", "", APPLICATION_PATH).$publicfolder."dompdf/temp/".$temp_file_name, $session->getVar('weeklystatusreport'));
		} // end check for 
		
	} // end check for unapproved timesheets
	require_once APPLICATION_PATH.'/includes/footer.php';
} // end check for whether the form has been submitted 
?>
