<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$projectassignment = new ProjectAssignment(); 
	
	// default title is to enable adding a new organisation
	$title = $this->translate("projectassignment_pagetitle_new"); 
	$posturl = $this->baseUrl("projectassignment/create");
	$button_title = $this->translate("projectassignment_button_new"); 
	
	// set the organisation if provided in the url 
	if (!isEmptyString($request->id)) {
		$projectassignment->populate(decode($request->id));
		$title = sprintf($this->translate("projectassignment_pagetitle_edit")); 
		$button_title = $this->translate("projectassignment_button_edit");
		$posturl = $this->baseUrl("projectassignment/edit"); 
	}
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$projectassignment->processPost($session->getVar(FORM_VALUES));	
	}
	
	$this->headTitle($title);  
	
?>
<script>
	$(document).ready(function() {
		// configure the date pickers
		var startdateOpts = datepickerOpts; 
		$("#startdate").datepicker(startdateOpts); 
		$("#enddate").datepicker(datepickerOpts); 
		
		$("#projectassignmentform").validate({		
			// define the validation rules one field at a time
			rules: {
				employeeid: "required",
				projectid: "required",
				enddate: {
					enddateafterstartdate: true
				}
			}, 
			// the messages for each of the fields being validated
			messages: {				
				employeeid: "<?php echo $this->translate("projectassignment_employee_error"); ?>",
				projectid: "<?php echo $this->translate("projectassignment_project_error"); ?>",
				startdate: "<?php echo $this->translate("projectassignment_startdate_error"); ?>",
				enddate: {
					enddateafterstartdate: "<?php echo $this->translate("projectassignment_enddate_afterstartdate_error"); ?>"
				}
			},
			// update error location for content type
			errorPlacement: function(error, element) {
				if (element.attr("id") == "startdate"){ 
					error.appendTo("#startdate_error");
				} else if (element.attr("id") == "enddate"){ 
					error.appendTo("#enddate_error");
				} else if (element.attr("id") == "employeeid"){ 
					error.appendTo("#employeeid_error");
				} else if (element.attr("id") == "projectid"){ 
					error.appendTo("#projectid_error");
				} else { 
					error.insertAfter(element);
				}
			}
		});
		
		// get an array of all projects and clients
		var projects = new Array();
		<?php $allprojectsandclients = $projectassignment->getAllProjectsAndClientsArray();
		foreach ($allprojectsandclients as $project){ ?>
			projects[<?php echo $project['id'] ?>] = <?php echo $project['clientid'] ?>;
		<?php } ?>
		
		// update the client id in the hidden field
		$('#projectid').change(function(e){
			var projectid = $("#projectid").val();
			$("#clientid").val(projects[projectid]);		
		});
	}); 
</script>

<form id="projectassignmentform" action="<?php echo $posturl; ?>" method="post">
  <table class="formtable">
    <thead>
      <tr>
        <td colspan="2"><?php echo $title; ?></td>
      </tr>
    </thead>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td colspan="2"><label class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></label></td>
    </tr>
    <?php } ?>
    <tr>
      <td colspan="2"><?php echo $this->translate("required_field_info"); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("projectassignment_employee_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><?php		
                $employeelookup = new LookupType(); 				
                $employeelookup->setName("ALL_USERS");				
                $employeedropdown = new Zend_Form_Element_Select('employeeid',
                                    array(
										'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $employeelookup->getOptionValuesFromQuery()),						
										'view' => new Zend_View(),
                                        'decorators' => array(array('ViewHelper', array('escape' => true))),
										'class' => array('chzn-select')					
                                    )
                                );
                                
                $employeedropdown->setValue($projectassignment->getEmployeeID());
                echo $employeedropdown->render(); 
        ?><div id="employeeid_error"></div></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("projectassignment_project_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><?php		
                $projectlookup = new LookupType(); 				
                $projectlookup->setName("ALL_PROJECTS");				
                $projectdropdown = new Zend_Form_Element_Select('projectid',
                                    array(
										'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $projectlookup->getOptionValuesFromQuery()),						
										'view' => new Zend_View(),
                                        'decorators' => array(array('ViewHelper', array('escape' => true))),
										'class' => array('chzn-select')					
                                    )
                                );
                                
                $projectdropdown->setValue($projectassignment->getProjectID());
                echo $projectdropdown->render(); 
        ?><div id="projectid_error"></div></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("projectassignment_startdate_label"); ?>:</td>
      <td><input type="text" class="datefield startdate" name="startdate" id="startdate" value="<?php echo changeMySQLDateToPageFormat($projectassignment->getStartDate()); ?>" />
        <div id="startdate_error"></div></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("projectassignment_enddate_label"); ?>:</td>
      <td><input type="text" class="datefield" name="enddate" id="enddate" value="<?php echo changeMySQLDateToPageFormat($projectassignment->getEndDate()); ?>" />
        <div id="enddate_error"></div></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("projectassignment_notes_label"); ?>:</td>
      <td><textarea class="expanding" name="notes" id="notes"><?php echo $projectassignment->getNotes(); ?></textarea></td>
    </tr>
    <tfoot>
      <tr>
        <td>&nbsp;</td>
        <td><a href="<?php echo $this->baseUrl("projectassignment/list"); ?>" title="<?php echo $this->translate('global_button_cancel'); ?>"><?php echo $this->translate('global_button_cancel'); ?></a>&nbsp;&nbsp;
          <button type="submit" class="positiveaction" id="submit" name="submit" title="<?php echo $button_title; ?>"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" /><?php echo $button_title; ?></button>
          <input type="hidden" name="entityname" value="ProjectAssignment" />
          <input type="hidden" id="id" name="id" value="<?php echo encode($projectassignment->getID()); ?>" />
          <input type="hidden" id="clientid" name="clientid" value="<?php echo $projectassignment->getClientID(); ?>" /></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
