<table border="0" cellspacing="1" cellpadding="0">
  <tr>
    <td><?php echo $this->firstname; ?>,</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Please enter your <?php echo $this->type; ?> for Week Ending <?php echo $this->weekendingdate; ?> at <a href="<?php echo $this->serverUrl($this->baseUrl()); ?>" target="_blank"><?php echo $this->serverUrl($this->baseUrl()); ?></a></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Thank you</td>
  </tr>
  <tr>
    <td><?php echo $this->signoffname."<br />".$this->signoffemail."<br />".$this->serverUrl($this->baseUrl()); ?></td>
  </tr>
</table>
