<table border="0" cellspacing="1" cellpadding="0">
  <tr>
    <td><?php echo $this->firstname; ?>,</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>This email confirms that your <?php echo $this->type; ?> for Week Ending <?php echo $this->weekendingdate; ?> has been <?php echo strtolower($this->approvalstatus); ?>.<br />
      <?php 
	if (!isEmptyString($this->reason)) {
		echo "<br />Reason: ".$this->reason;
	}
	?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  <tr>
    <td>Click here to view the details: <?php echo $this->serverUrl($this->url($this->urltoview)); ?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><?php echo $this->signoffname."<br />".$this->signoffemail."<br />".$this->serverUrl($this->baseUrl()); ?></td>
  </tr>
</table>
