<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = $this->translate("useraccount_pagetitle_changepassword");
	$this->headTitle($title); 
	
	$useraccount = new UserAccount(); 	
	$useraccount->populate($userid);
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$useraccount->processPost($session->getVar(FORM_VALUES));	
	}
	
?>
<script>
	$(document).ready(function() {		
		$("#changepasswordform").validate({		
			// define the validation rules one field at a time
			rules: {
				oldpassword: {
					required: true				
				},
				password: {
					required: true
				},
				confirmpassword: {
					required: true,
					equalTo: "#password"
				}				
			}, 
			// the messages for each of the fields being validated
			messages: {				
				oldpassword: {
					required: "<?php echo $this->translate("useraccount_oldpassword_error"); ?>"
				},
				password: {
					required: "<?php echo $this->translate("useraccount_password_error"); ?>"
				}, 
				confirmpassword: {
					required: "<?php echo $this->translate("useraccount_confirmpassword_error"); ?>",
					equalTo: "<?php echo $this->translate("useraccount_confirmpassword_error_equalto"); ?>"
				}
			}
		});
		
		$("#submit").click(function(){
			if($("#changepasswordform").valid()){
				if(window.confirm("Are you sure you want to change your Password. \n Click OK to proceed or Cancel to stay on current page")){
					$("#changepasswordform").submit();
				} else {
					return false;
				}
			} 
		});
	}); 
</script>
<form id="changepasswordform" action="<?php echo $this->baseUrl("profile/changepassword");?>" method="post">
	<table class="formtable">
		<thead>
			<tr>
				<td colspan="2"><?php echo $title; ?></td>
			</tr>
		</thead>
		<?php if ($sessionhaserror) { ?>
		<tr>
			<td colspan="2"><label class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></label></td>
		</tr>
		<?php } ?>
		<tr>
			<td colspan="2">Please note that you will have to login using your new password</td>
		</tr>
		<tr>
			<td colspan="2"><?php echo $this->translate("required_field_info"); ?></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_password_current_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></td>
			<td><input name="oldpassword" id="oldpassword" type="password" class="passwordfield" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_password_new_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></td>
			<td><input name="password" id="password" type="password" class="password" />
				<div class="password-meter">
					<div class="password-meter-message"> </div>
					<div class="password-meter-bg">
						<div class="password-meter-bar"></div>
					</div>
				</div></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_password_confirm_label"); ?>: <span style="color:#FF0000;">*</span></td>
			<td><input name="confirmpassword" id="confirmpassword" type="password" /></td>
		</tr>
		<tfoot>
		<tr>
			<td>&nbsp;</td>
			<td><a href="<?php echo $this->baseUrl("profile/view"); ?>" title="<?php echo $this->translate("global_button_cancel"); ?>"><img src="<?php echo $this->baseUrl("images/cross.png"); ?>" alt="<?php echo $this->translate("global_button_cancel"); ?>" /><?php echo $this->translate("global_button_cancel"); ?></a>&nbsp;&nbsp;
				<button type="submit" class="positiveaction" id="submit" name="submit" title="<?php echo $this->translate("useraccount_button_changepassword");?>"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" alt="<?php echo $this->translate("useraccount_button_changepassword");?>" /><?php echo $this->translate("useraccount_button_changepassword");?></button>
				<input type="hidden" name="entityname" value="UserAccount" />
				<input type="hidden" id="id" name="id" value="<?php echo encode($useraccount->getID()); ?>" /></td>
		</tr>
		</tfoot>
	</table>
</form>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
