<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Set page title
	$title = $this->translate("useraccount_pagetitle_changepassword_confirmation");
	$this->headTitle($title); 
?>
<h2><?php echo $title; ?></h2>
<table>
	<tr>
    	<td><label class="successmessage">You have sucessfully changed your password</label></td>
    </tr>
    <tr>
    	<td><br /><a href="<?php echo $this->baseUrl("user/logout");?>">Click here</a> to login using your new password</td>
    </tr>
     <tr>
    	<td>&nbsp;</td>
    </tr>
</table>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>