<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = $this->translate('useraccount_pagetitle_list');
	$this->headTitle($title);
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("u.firstname","u.lastname","u.email","u.phonenumber"));
	$paginate->setFilterColumns(array("u.isactive", "aug.groupid"));
	$paginate->setDefaultSortBy("u.firstname");	
	$paginate->setDefaultSortOrder("ASC");
	
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT u.id, concat(u.firstname, ' ', u.lastname) as `Name`, u.jobtitle as `Job Title`, u.email as `Email Address`, acg.`name` AS `Employee Type`, lv.lookupvaluedescription AS `Status` FROM useraccount AS u INNER JOIN aclusergroup AS aug ON u.id = aug.userid INNER JOIN aclgroup AS acg ON aug.groupid = acg.id INNER JOIN lookuptypevalue AS lv ON u.isactive = lv.lookuptypevalue INNER JOIN lookuptype AS l ON lv.lookuptypeid = l.id WHERE email <> '' AND l.`name` = 'ACTIVE_STATUS' ".$paginate->getSearchAndFilterSQL()." ".$paginate->getSortSQL();
	//debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	# the query string to be appended to the return to list URL
	$session->setVar('list_query_string'.$request->getControllerName(), $request->getParams());
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	# This variable stores the number of redundant columns returned in the query so that when we are printing
	# we are able to know how many columns to ignore. This variable is sent in the print URL
	$number_of_redundant_columns = 1;
	
	# the columns which contain numbers in the invoice query
	# Please note that the column count begins at 0
	$export_number_column_list = "";
	
?>
<form action="<?php echo $this->baseUrl("profile/listsearch"); ?>" method="get" id="usersform">
  <table class="filtercontainer">
    <tr>
      <td><table class="filtersection">
          <tr>
            <td><?php			
                        $statuslookup = new LookupType(); 
                        $statuslookup->setName("ACTIVE_STATUS");
                        $activedropdown = new Zend_Form_Element_Select('u'.HTML_TABLE_COLUMN_SEPARATOR.'isactive',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array("" => $this->translate('useraccount_list_filter_status')), $statuslookup->getOptionValuesAndDescription()), 
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper')
                                    )
                        );
                        $activedropdown->setValue($request->getParam('u'.HTML_TABLE_COLUMN_SEPARATOR.'isactive')); 
                        echo $activedropdown->render();	
                    ?></td>
            <td><?php 	
			$lookupaclgroups = new LookupType();
			$lookupaclgroups->setName("ALL_ACL_GROUPS"); 
			$usertypedropdown = new Zend_Form_Element_Select('aug'.HTML_TABLE_COLUMN_SEPARATOR.'groupid',
    					array(
							'multiOptions' => array_merge_maintain_keys(array("" => $this->translate('useraccount_list_filter_employeetype')), $lookupaclgroups->getOptionValuesFromQuery()), 
							'view' => new Zend_View(),
							'decorators' => array('ViewHelper')
						)
    				);
    		$usertypedropdown->setValue($request->getParam('aug'.HTML_TABLE_COLUMN_SEPARATOR.'groupid')); 
    		echo $usertypedropdown->render();	
    	?></td>
          </tr>
        </table></td>
      <td><table>
          <tr>
            <td><input class="filterselect" type="text" name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" title="<?php echo $this->translate('gloabl_search_term_text'); ?>" /></td>
          </tr>
          <tr>
            <td><button type="submit" class="positiveaction" id="searchbutton" title="<?php echo $this->translate('list_searchbutton_title'); ?>"><img src="<?php echo $this->baseUrl("images/zoom_in.png"); ?>" alt="<?php echo $this->translate('list_searchbutton_title'); ?>"/><?php echo $this->translate('list_searchbutton_label'); ?></button></td>
          </tr>
        </table></td>
    </tr>
  </table>
  <?php // show a message that there are no items to display
	if ($has_no_data) {
?>
  <label class="informationmessage"><?php echo $this->translate("useraccount_list_norecords"); ?></label>
  <?php } else { ?>
  <div id="counter"><?php echo sprintf($this->translate("useraccount_list_counter"), $paginate->getItemCounterText()); ?></div>
  <div id="listcounter"><?php echo $this->listcountdropdown; ?></div>
  <div id="print"><a title="<?php echo $this->translate('global_print_as'); ?>" href="<?php echo $this->baseUrl('index/printerfriendly/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns.'/'.PAGE_TITLE.'/'.$title); ?>" target="_blank"><?php echo $this->translate('global_print'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/printer.png'); ?>" alt="<?php echo $this->translate('global_print_as'); ?>" /></a></div>
  <?php if ($acl->checkPermission('User Account', ACTION_EXPORT)) { ?>
  <div id="export"><a title="<?php echo $this->translate('global_export_as_excel'); ?>" href="<?php echo $this->baseUrl('index/exceldownload/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns); ?>" target="_blank"><?php echo $this->translate('global_export_as'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/excel.png'); ?>" alt="<?php echo $this->translate('global_export_as_excel'); ?>" /></a></div>
  <?php } ?>
  <table class="list">
    <caption>
    <?php echo $title; ?>
    </caption>
    <thead>
      <tr>
        <?php if ($acl->checkPermission('User Account', ACTION_EDIT)) { ?>
        <td><?php echo $this->translate("global_list_action_edit"); ?></td>
        <?php } ?>
        <td><?php echo $paginate->getSortLinkForColumn('u.firstname', $this->translate('useraccount_name_label')); ?></td>
        <td><?php echo $paginate->getSortLinkForColumn('u.jobtitle', $this->translate("useraccount_jobtitle_label")); ?></td>
        <td><?php echo $paginate->getSortLinkForColumn('u.email', $this->translate("useraccount_email_label")); ?></td>
        <td><?php echo $paginate->getSortLinkForColumn('acg.name', $this->translate("useraccount_usertype_label")); ?></td>
        <td><?php echo $paginate->getSortLinkForColumn('isactive',$this->translate("useraccount_isactive_label")); ?></td>
      </tr>
    </thead>
    <tbody>
      <?php 				  		
            	foreach($result as $line){							
            ?>
      <tr>
        <?php if ($acl->checkPermission('User Account', ACTION_EDIT)) { ?>
        <td align="center"><a href="<?php echo $this->baseUrl("profile/index/id/".encode($line['id'])); ?>" title="<?php echo $this->translate("useraccount_button_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" alt="<?php echo $this->translate("useraccount_button_edit"); ?>" /></a></td>
        <?php } ?>
        <td><a href="<?php echo $this->baseUrl("profile/view/id/".encode($line['id'])); ?>" title="<?php echo $this->translate("useraccount_button_view"); ?>"><?php echo $line['Name']; ?></a></td>
        <td><?php echo $line['Job Title']; ?></td>
        <td><?php echo $line['Email Address']; ?></td>
        <td><?php echo $line['Employee Type']; ?></td>
        <td><?php echo $line['Status']; ?></td>
      </tr>
      <?php 						
            	} // end processing results 
            ?>
    </tbody>
      </tr>
    
  </table>
  <?php			
	} // end check that there are results    	
?>
  <div class="paginationlinks"><?php echo $paginate->getPaginationLinks(); ?></div>
</form>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
