<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	$title = $this->translate("useraccount_pagetitle_recoverpassword_confirm");
	$this->headMeta()->appendName('keywords', '');
	$this->headMeta()->appendName('description', $title);
	$this->headTitle($title); 

?>

<table class="formtable">
  <thead>
    <tr>
      <td colspan="2"><?php echo $title; ?></td>
    </tr>
  </thead>
  <tr>
    <td colspan="2"><b>Note:</b>&nbsp;&nbsp;An email has been sent to you with details on how to reset your password. If you don't see the email in your inbox, please check your <b>Junk</b> or <b>Spam</b> mail folder.<br />
      <br />
      Note that it may take a while for you to receive the activation email depending on your email service provider.
      If you do not receive the email or have any other problems, let us know.</td> 
  </tr>
</table>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
