<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	$title = $this->translate("useraccount_pagetitle_recoverpassword"); 
	$this->headMeta()->appendName('keywords', '');
	$this->headMeta()->appendName('description', $title);
	$this->headTitle($title);

	$useraccount = new UserAccount(); 
	
	if ($sessionhaserror) {
		$formvalues = $session->getVar(FORM_VALUES); 
		$useraccount->setEmail($formvalues['email']); 
	}
?>
<script>
$(document).ready(function(){
	$("#recoverpasswordform").validate({
		rules: {
			email: {
				required: true,
				email: true
			}
		}, 
		messages: {
			email: {
				required: "<?php echo $this->translate("useraccount_email_error"); ?>",
				email: "<?php echo $this->translate("useraccount_email_invalid_error"); ?>"
			}
		}
	}); 
}); 
</script>

<form id="recoverpasswordform" action="" method="post">
  <table class="formtable">
    <thead>
      <tr>
        <td colspan="2"><?php echo $title; ?></td>
      </tr>
    </thead>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td colspan="2"><label class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></label></td>
    </tr>
    <?php } ?>
    <tr>
      <td colspan="2">To reset your password, type the full email address you use to sign in to your account.</td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("useraccount_email_label"); ?>: </td>
      <td><input name="email" type="text" value="<?php echo $useraccount->getEmail(); ?>" /></td>
    </tr>
    <tfoot>
      <tr>
        <td>&nbsp;</td>
        <td><a class="negativeaction" href="<?php echo $this->baseUrl('user/login'); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate('global_button_cancel'); ?></a>&nbsp;&nbsp;
          <button type="submit" class="positiveaction"><img src="<?php echo $this->baseUrl('images/login.png'); ?>" /><?php echo $this->translate('useraccount_button_recoverpassword'); ?></button></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
