<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	$title = $this->translate("useraccount_pagetitle_resetpassword_confirm");
	$this->headMeta()->appendName('keywords', '');
	$this->headMeta()->appendName('description', $title);
	$this->headTitle($title);

?>

<table class="formtable">
  <thead>
    <tr>
      <td colspan="2"><?php echo $title; ?></td>
    </tr>
  </thead>
  <tr>
    <td colspan="2">You have sucessfully changed your password.<br />
      <br />
      <a href="<?php echo $this->baseUrl('user/logout')?>">Click here</a> to login using your new password</td>
  </tr>
</table>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
