<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	$title = $this->translate("useraccount_pagetitle_resetpassword"); 
	$this->headMeta()->appendName('keywords', '');
	$this->headMeta()->appendName('description', $title);
	$this->headTitle($title);

	$useraccount = new UserAccount(); 
	$useraccount->populate(decode($request->id));
	
	if ($sessionhaserror) {
		$formvalues = $session->getVar(FORM_VALUES); 
		$useraccount->setEmail($formvalues['email']); 
	}
?>
<script>
	$(document).ready(function(){
		// validation code for the form
		$("#resetpasswordform").validate({
			rules: {
				confirmpassword: {
					required: true,
					equalTo: "#password"
				}
			},
			messages: {
				confirmpassword: {
					required: "<?php echo $this->translate("useraccount_confirmpassword_error"); ?>",
					equalTo: "<?php echo $this->translate("useraccount_confirmpassword_error_equalto"); ?>"
				}
			}
		}); 
	}); 
</script>

<form id="resetpasswordform" method="post" action="<?php echo $this->baseUrl("user/resetpassword"); ?>">
  <table class="formtable">
    <thead>
      <tr>
        <td colspan="2"><?php echo $title; ?></td>
      </tr>
    </thead>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td colspan="2"><label class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></label></td>
    </tr>
    <?php } ?>
    <tr>
      <td colspan="2"><?php echo $this->translate("required_field_info"); ?></td>
    </tr>
    <tr>
      <td colspan="2"><label class="informationmessage">Please note that you will have to login with your new Password.</label></td>
    </tr>
    <?php if (isNotAnEmptyString($request->id)) { ?>
    <tr>
      <td class="label"><?php echo $this->translate("useraccount_employee_label"); ?>:</td>
      <td><?php echo $useraccount->getName(); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label"><?php echo $this->translate("useraccount_password_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><input class="password" id="password" name="password" type="password" />
        <div class="password-meter">
        <div class="password-meter-message"> </div>
        <div class="password-meter-bg">
          <div class="password-meter-bar"></div>
        </div></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("useraccount_password_confirm_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><input id="confirmpassword" name="confirmpassword" type="password" /></td>
    </tr>
    <tfoot>
      <tr>
        <td>&nbsp;</td>
        <td><a class="negativeaction" href="<?php echo $this->baseUrl('index'); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate('global_button_cancel'); ?></a>&nbsp;&nbsp;
          <button type="submit" class="positiveaction"><img src="<?php echo $this->baseUrl('images/login.png'); ?>" /><?php echo $this->translate('useraccount_button_resetpassword'); ?></button>
          <input name="<?php echo URL_FAILURE; ?>" type="hidden" value="<?php echo encode($this->url(array("faiulre" => "xx"))); ?>" />
          <input name="id" type="hidden" value="<?php echo $request->id; ?>" /></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
