<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = $this->translate('project_pagetitle_list');
	$this->headTitle($title);
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("p.title"));
	$paginate->setFilterColumns(array("p.clientid"));
	$paginate->setDefaultSortBy("p.title");	
	$paginate->setDefaultSortOrder("ASC");

	$paginate->processPost($request->getParams());
	
	$all_results_query = "SELECT p.id, p.clientid, p.title as `Project Title`, p.jobnumber as `Job Number`, lv.lookupvaluedescription as `Type`, DATE_FORMAT(p.startdate, '".$config->dateandtime->mysqlformat."') as 'Start Date', DATE_FORMAT(p.enddate, '".$config->dateandtime->mysqlformat."') as 'End Date', c.`name` AS `Client` FROM project as p INNER JOIN client AS c ON p.clientid = c.id INNER JOIN lookuptypevalue AS lv ON (p.`type` = lv.lookuptypevalue AND lv.lookuptypeid = 5) WHERE p.id <> '' ".$paginate->getSearchAndFilterSQL()." ".$paginate->getSortSQL();
	//debugMessage($all_results_query);
	
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	# the query string to be appended to the return to list URL
	$session->setVar('list_query_string'.$request->getControllerName(), $request->getParams());
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	# This variable stores the number of redundant columns returned in the query so that when we are printing
	# we are able to know how many columns to ignore. This variable is sent in the print URL
	$number_of_redundant_columns = 2;
	
	# the columns which contain numbers in the invoice query
	# Please note that the column count begins at 0
	$export_number_column_list = "";
	
?>
<style></style>
<form action="<?php echo $this->baseUrl("project/listsearch"); ?>" method="get" id="projectform">
  <table class="filtercontainer">
    <tr>
      <td><table class="filtersection">
          <tr>
            <td><?php			
                        $clientlookup = new LookupType(); 
                        $clientlookup->setName("ALL_CLIENTS");
                        $clientdropdown = new Zend_Form_Element_Select('p'.HTML_TABLE_COLUMN_SEPARATOR.'clientid',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array("" => $this->translate('project_list_filter_client')), $clientlookup->getOptionValuesFromQuery()), 
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
										'class' => array('chzn-select')
                                    )
                        );
                        $clientdropdown->setValue($request->getParam('p'.HTML_TABLE_COLUMN_SEPARATOR.'clientid')); 
                        echo $clientdropdown->render();	
                    ?></td>
          </tr>
        </table></td>
      <td><table>
          <tr>
            <td><input class="filterselect" type="text" name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" title="<?php echo $this->translate('gloabl_search_term_text'); ?>" /></td>
          </tr>
          <tr>
            <td><button type="submit" class="positiveaction" id="searchbutton" title="<?php echo $this->translate('list_searchbutton_title'); ?>"><img src="<?php echo $this->baseUrl("images/zoom_in.png"); ?>" alt="<?php echo $this->translate('list_searchbutton_title'); ?>"/><?php echo $this->translate('list_searchbutton_label'); ?></button></td>
          </tr>
        </table></td>
    </tr>
  </table>
  <?php // show a message that there are no items to display
	if ($has_no_data) {
?>
  <label class="informationmessage"><?php echo $this->translate('project_list_norecords'); ?></label>
  <?php } else { ?>
  <div id="counter"><?php echo sprintf($this->translate("project_list_counter"), $paginate->getItemCounterText()); ?></div>
  <div id="listcounter"><?php echo $this->listcountdropdown; ?></div>
  <div id="print"><a title="<?php echo $this->translate('global_print_as'); ?>" href="<?php echo $this->baseUrl('index/printerfriendly/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns.'/'.PAGE_TITLE.'/'.$title); ?>" target="_blank"><?php echo $this->translate('global_print'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/printer.png'); ?>" alt="<?php echo $this->translate('global_print_as'); ?>" /></a></div>
  <?php if ($acl->checkPermission('Client', ACTION_EXPORT)) { ?>
  <div id="export"><a title="<?php echo $this->translate('global_export_as_excel'); ?>" href="<?php echo $this->baseUrl('index/exceldownload/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns); ?>" target="_blank"><?php echo $this->translate('global_export_as'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/excel.png'); ?>" alt="<?php echo $this->translate('global_export_as_excel'); ?>" /></a></div>
  <?php } ?>
  <table class="list">
    <caption>
    <?php echo $title; ?>
    </caption>
    <thead>
      <tr>
        <?php if ($acl->checkPermission('Project', ACTION_EDIT)) { ?>
        <td>Edit</td>
        <?php }?>
        <td><?php echo $paginate->getSortLinkForColumn('p.title', $this->translate("project_title_label")); ?></td>
        <td><?php echo $this->translate('project_jobnumber_label'); ?></td>
        <td><?php echo $this->translate('project_type_label'); ?></td>
        <td><?php echo $this->translate('project_startdate_label'); ?></td>
        <td><?php echo $this->translate('project_enddate_label'); ?></td>
        <td><?php echo $this->translate('project_client_label'); ?></td>
      </tr>
    </thead>
    <tbody>
      <?php 				  		
			foreach($result as $line){							
		?>
      <tr>
        <?php if ($acl->checkPermission('Project', ACTION_EDIT)) { ?>
        <td align="center"><a href="<?php echo $this->baseUrl("project/index/id/".encode($line['id'])); ?>" title="<?php echo $this->translate("project_button_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" alt="<?php echo $this->translate("project_button_edit"); ?>" /></a></td>
        <?php }?>
        <td><a href="<?php echo $this->baseUrl("project/view/id/".encode($line['id'])); ?>" title="<?php echo $this->translate("project_button_view"); ?>"><?php echo $line['Project Title']; ?></a></td>
        <td><?php echo $line['Job Number']; ?></td>
        <td><?php echo $line['Type']?></td>
        <td><?php echo $line['Start Date']; ?></td>
        <td><?php echo $line['End Date']; ?></td>
        <td><?php echo $line['Client']; ?></td>
      </tr>
      <?php 						
			} // end processing results 
		?>
    </tbody>
  </table>
  <?php			
	} // end check that there are results    	
?>
  <div class="paginationlinks"><?php echo $paginate->getPaginationLinks(); ?></div>
</form>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
