<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = $this->translate('folder_pagetitle_list');
	$this->headTitle($title);
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("f.name"));	
	$paginate->setDefaultSortBy("f.datecreated");	
	$paginate->setDefaultSortOrder("DESC");

	$paginate->processPost($request->getParams());
	
	$all_results_query = "SELECT f.id, f.name as `Folder Name`, f.description as `Description` FROM folder AS f WHERE f.id <> '' ".$paginate->getSearchAndFilterSQL()." ".$paginate->getSortSQL();
	// debugMessage($all_results_query);
	
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	# the query string to be appended to the return to list URL
	$session->setVar('list_query_string'.$request->getControllerName(), $request->getParams());
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	# This variable stores the number of redundant columns returned in the query so that when we are printing
	# we are able to know how many columns to ignore. This variable is sent in the print URL
	$number_of_redundant_columns = 1;
	
	# the columns which contain numbers in the invoice query
	# Please note that the column count begins at 0
	$export_number_column_list = "";
	
?>
<style></style>
<form action="<?php echo $this->baseUrl("folder/listsearch"); ?>" method="get" id="taskform">
  <table class="filtercontainer">
    <tr>
      <td><table class="filtersection">
          <tr>
            <td></td>            
          </tr>
        </table></td>
      <td><table>
          <tr>
            <td><input class="filterselect" type="text" name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" title="<?php echo $this->translate('gloabl_search_term_text'); ?>" /></td>
          </tr>
          <tr>
            <td><button type="submit" class="positiveaction" id="searchbutton" title="<?php echo $this->translate('list_searchbutton_title'); ?>"><img src="<?php echo $this->baseUrl("images/zoom_in.png"); ?>" alt="<?php echo $this->translate('list_searchbutton_title'); ?>"/><?php echo $this->translate('list_searchbutton_label'); ?></button></td>
          </tr>
        </table></td>
    </tr>
  </table>
  <?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
  <label class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></label>
  <?php } ?>
  <?php if(isNotAnEmptyString($session->getVar(ERROR_MESSAGE))){ ?>
  <label class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></label>
  <?php } ?>
  <?php // show a message that there are no items to display
	if ($has_no_data) {
?>
  <label class="informationmessage"><?php echo $this->translate('folder_list_norecords'); ?></label>
  <?php } else { ?>
  <div id="counter"><?php echo sprintf($this->translate("folder_list_counter"), $paginate->getItemCounterText()); ?></div>
  <div id="listcounter"><?php echo $this->listcountdropdown; ?></div>  
  <table class="list">
    <caption>
    <?php echo $title; ?>
    </caption>
    <thead>
      <tr>
        <?php if ($acl->checkPermission('Folder', ACTION_EDIT)) { ?>
        <td width="30">Edit</td>
        <?php }?>
        <td width="200"><?php echo $paginate->getSortLinkForColumn('f.name', $this->translate("folder_name_label")); ?></td>
        <td><?php echo $paginate->getSortLinkForColumn('f.description', $this->translate('folder_description_label')); ?></td>       
      </tr>
    </thead>
    <tbody>
      <?php foreach($result as $line){ ?>
      <tr>
        <?php if ($acl->checkPermission('Folder', ACTION_EDIT)) { ?>
        <td align="center"><a href="<?php echo $this->baseUrl("folder/index/id/".encode($line['id'])); ?>" title="<?php echo $this->translate("folder_button_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" alt="<?php echo $this->translate("folder_button_edit"); ?>" /></a></td>
        <?php }?>
        <td><a href="<?php echo $this->baseUrl("folder/view/id/".encode($line['id'])); ?>" title="<?php echo $this->translate("folder_button_view"); ?>"><?php echo $line['Folder Name']; ?></a></td>
        <td class="nowrapping"><?php echo $line['Description']; ?></a></td>        
      </tr>
      <?php 						
			} // end processing results 
		?>
    </tbody>
  </table>
  <?php			
	} // end check that there are results    	
?>
  <div class="paginationlinks"><?php echo $paginate->getPaginationLinks(); ?></div>
</form>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
